/****************************************************************************
 * arch/arm/src/stm32n6/hardware/stm32_aton.h
 *
 * Neural-ART (ATON) NPU block registers.
 *
 * The NPU register window is STM32_NPU_BASE (AHB5 + 0x0C0000 = 0x580E0000,
 * secure alias).  The full register map is generated by ST (ATON.h, 100k
 * lines, vendored under libs/ai_aton/vendor/Devices/STM32N6XX) and is far too
 * large to include from the chip layer; this header only carries the few
 * registers the NuttX driver touches directly.
 *
 * The VERSION register of each block lives at (block base + 0x4) and reads
 * back a non-zero identification value once the block is clocked and
 * reachable, which makes these registers a compact readiness probe for the
 * NPU clock/reset/bus path (no model and no runtime required).
 *
 * Offsets were resolved from the vendored ATON.h:
 *
 *   ATON_<BLOCK>_VERSION_ADDR(0) - ATON_BASE
 *
 *   CLKCTRL +0x0004   BUSIF   +0x2004   INTCTRL +0x1004   STRENG +0x5004
 *   CONVACC +0xf004   DECUN   +0x13004  ACTIV   +0x15004  ARITH  +0x17004
 *   POOL    +0x1b004
 *
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.  The
 * ASF licenses this file to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance with the
 * License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations
 * under the License.
 *
 ****************************************************************************/

#ifndef __ARCH_ARM_SRC_STM32N6_HARDWARE_STM32_ATON_H
#define __ARCH_ARM_SRC_STM32N6_HARDWARE_STM32_ATON_H

/****************************************************************************
 * Included Files
 ****************************************************************************/

#include "hardware/stm32_memorymap.h"

/****************************************************************************
 * Pre-processor Definitions
 ****************************************************************************/

/* ATON block identification registers */

#define STM32_ATON_CLKCTRL_VERSION  (STM32_NPU_BASE + 0x0004)
#define STM32_ATON_BUSIF_VERSION    (STM32_NPU_BASE + 0x2004)
#define STM32_ATON_INTCTRL_VERSION  (STM32_NPU_BASE + 0x1004)
#define STM32_ATON_STRENG_VERSION   (STM32_NPU_BASE + 0x5004)
#define STM32_ATON_CONVACC_VERSION  (STM32_NPU_BASE + 0xf004)
#define STM32_ATON_DECUN_VERSION    (STM32_NPU_BASE + 0x13004)
#define STM32_ATON_ACTIV_VERSION    (STM32_NPU_BASE + 0x15004)
#define STM32_ATON_ARITH_VERSION    (STM32_NPU_BASE + 0x17004)
#define STM32_ATON_POOL_VERSION     (STM32_NPU_BASE + 0x1b004)

/* Epoch controller.  It owns the blob fetch ("ADDR" is the address the
 * runtime hands the NPU, "BC" the blob opcode counter, "IRQ" the latched
 * error flags: ERR_BUSPORT, ERR_CONF, ERR_START, ERR_TIMEOUT, ERR_UNKOP,
 * ERR_SRC, ERR_EVT).  CTRL.RUNNING (bit 31) says whether the NPU is
 * executing at all.
 */

#define STM32_ATON_EC_CTRL          (STM32_NPU_BASE + 0x1e000)
#define STM32_ATON_EC_ADDR          (STM32_NPU_BASE + 0x1e008)
#define STM32_ATON_EC_IRQ           (STM32_NPU_BASE + 0x1e00c)
#define STM32_ATON_EC_LABEL         (STM32_NPU_BASE + 0x1e01c)
#define STM32_ATON_EC_BC            (STM32_NPU_BASE + 0x1e020)
#define STM32_ATON_EC_ACC           (STM32_NPU_BASE + 0x1e024)
#define STM32_ATON_EC_CIDCACHE      (STM32_NPU_BASE + 0x1e018)

/* Interrupt controller: status and routing masks (RM0486 section 20.3.16).
 * The host reads INTREG to identify which unit is asking for attention.
 */

#define STM32_ATON_INTCTRL_INTREG   (STM32_NPU_BASE + 0x1008)
#define STM32_ATON_INTCTRL_ORMSK0   (STM32_NPU_BASE + 0x1014)
#define STM32_ATON_INTCTRL_ORMSK1   (STM32_NPU_BASE + 0x1018)
#define STM32_ATON_INTCTRL_ANDMSK0  (STM32_NPU_BASE + 0x1024)
#define STM32_ATON_INTCTRL_ANDMSK1  (STM32_NPU_BASE + 0x1028)

/* Stream engines, one per input/output stream link (RM0486 Table 112).
 * CTRL tells whether the engine was started / is running, ADDR where it is
 * currently reading or writing.  A running engine points at the tensor that
 * the dataflow is stuck on.
 */

#define STM32_ATON_STRENG_CTRL(i)   (STM32_NPU_BASE + 0x5000 + (i) * 0x1000)
#define STM32_ATON_STRENG_ADDR(i)   (STM32_ATON_STRENG_CTRL(i) + 0x08)
#define STM32_ATON_NSTRENG          10

/* Debug and trace unit (offset 0x1f000): stream switch link monitors.  The
 * link state/stall registers show which link of the dataflow graph is
 * blocked, which is otherwise invisible from outside the NPU.
 */

/* Central stream switch (RM0486 Table 112: offset 0x4000).  It routes the
 * streams between units and generates the per-destination frame start
 * tokens (link + frame-number contexts, two per destination).  A
 * destination whose register is left empty never sees a frame start, and
 * the stream engine attached to it waits forever.
 */

#define STM32_ATON_STRSWITCH        (STM32_NPU_BASE + 0x4000)
#define STM32_ATON_STRSWITCH_CTRL   (STM32_ATON_STRSWITCH + 0x00)
#define STM32_ATON_STRSWITCH_VERSION (STM32_ATON_STRSWITCH + 0x04)
#define STM32_ATON_STRSWITCH_DST(i) (STM32_ATON_STRSWITCH + 0x08 + (i) * 4)
#define STM32_ATON_STRSWITCH_NDST   41
#define STM32_ATON_BLK_RECBUF       (STM32_NPU_BASE + 0x1d000)

#define STM32_ATON_TRACE_CTRL       (STM32_NPU_BASE + 0x1f000)
#define STM32_ATON_TRACE_ILINK_LO   (STM32_NPU_BASE + 0x1f008)
#define STM32_ATON_TRACE_ILINK_HI   (STM32_NPU_BASE + 0x1f00c)
#define STM32_ATON_TRACE_OLINK_LO   (STM32_NPU_BASE + 0x1f010)
#define STM32_ATON_TRACE_OLINK_HI   (STM32_NPU_BASE + 0x1f014)

/* Per-block control registers (each unit exposes CTRL at its block base +0)
 * and the clock control unit's per-unit gates.  A unit whose CTRL.EN is 0, or
 * whose clock gate is off, makes the epoch controller stop on the opcode that
 * needs it - without raising any error interrupt.
 */

#define STM32_ATON_BLK_CLKCTRL      (STM32_NPU_BASE + 0x0000)
#define STM32_ATON_BLK_INTCTRL      (STM32_NPU_BASE + 0x1000)
#define STM32_ATON_BLK_BUSIF0       (STM32_NPU_BASE + 0x2000)
#define STM32_ATON_BLK_BUSIF1       (STM32_NPU_BASE + 0x3000)
#define STM32_ATON_BLK_STRENG       (STM32_NPU_BASE + 0x5000)
#define STM32_ATON_BLK_CONVACC      (STM32_NPU_BASE + 0xf000)
#define STM32_ATON_BLK_DECUN        (STM32_NPU_BASE + 0x13000)
#define STM32_ATON_BLK_ACTIV        (STM32_NPU_BASE + 0x15000)
#define STM32_ATON_BLK_ARITH        (STM32_NPU_BASE + 0x17000)
#define STM32_ATON_BLK_POOL         (STM32_NPU_BASE + 0x1b000)
#define STM32_ATON_BLK_EPOCHCTRL    (STM32_NPU_BASE + 0x1e000)

#define STM32_ATON_CLKCTRL_AGATES0  (STM32_ATON_BLK_CLKCTRL + 0x08)
#define STM32_ATON_CLKCTRL_AGATES1  (STM32_ATON_BLK_CLKCTRL + 0x0c)
#define STM32_ATON_CLKCTRL_BGATES   (STM32_ATON_BLK_CLKCTRL + 0x10)

/* Bus interface (BUSIF0 at +0x2000, BUSIF1 at +0x3000).  ERR latches one
 * error bit per AXI bus port ("Errors from AXI bus related to busport N");
 * unlike the epoch controller flags, a stalled NPU leaves its footprint
 * here.  Write 1 to clear.
 */

#define STM32_ATON_BUSIF0_CTRL      (STM32_NPU_BASE + 0x2000)
#define STM32_ATON_BUSIF0_ERR       (STM32_NPU_BASE + 0x2010)
#define STM32_ATON_BUSIF1_CTRL      (STM32_NPU_BASE + 0x3000)
#define STM32_ATON_BUSIF1_ERR       (STM32_NPU_BASE + 0x3010)

#endif /* __ARCH_ARM_SRC_STM32N6_HARDWARE_STM32_ATON_H */
